### ISSUE TITLE
there is no actual code 

### ISSUE THREAD

**Issue by Mimoja** [fako1024/btscale#1]
Maybe just an oversight?

**Comment by fako1024** [comment]
No, code is just not ready to be committed yet. Will follow in the coming days.

**Comment by Mimoja** [comment]
Okay :)
I have working support for the Acaia scales, Skale 1/2 and the decent scale and am looking for how to tare a felicita scale.
If you want me to review something just ping me :)

**Comment by fako1024** [comment]
Nice! Yeah, the current initial implementation is actually based on the Felicita (since that's currently the only model I have) but of course aims at being generic. I'll be happy to ping you - In the meantime feel also free to have a quick look at the develop branch with the current WIP (includes also capabilities to tare / interact with the Felicita). Currently doing some testing, but it should already be working (no guarantees yet though ;-))
